/**
 * Default merchant keyword → category name mappings for Indian merchants.
 *
 * Keywords are stored lowercase. At runtime, the SMS merchant string is
 * normalized and checked for substring matches against these keywords.
 *
 * Category names must match the default category names in categories.ts exactly.
 */

export interface DefaultMerchantMapping {
  keyword: string;
  categoryName: string;
  confidence: number;
}

export const DEFAULT_MERCHANT_MAPPINGS: DefaultMerchantMapping[] = [
  // ────────────────────────────────────────────
  // Food & Dining
  // ────────────────────────────────────────────
  { keyword: "swiggy", categoryName: "Food", confidence: 0.95 },
  { keyword: "zomato", categoryName: "Food", confidence: 0.95 },
  { keyword: "ubereats", categoryName: "Food", confidence: 0.95 },
  { keyword: "uber eats", categoryName: "Food", confidence: 0.95 },
  { keyword: "dominos", categoryName: "Food", confidence: 0.95 },
  { keyword: "domino's", categoryName: "Food", confidence: 0.95 },
  { keyword: "pizza hut", categoryName: "Food", confidence: 0.9 },
  { keyword: "kfc", categoryName: "Food", confidence: 0.9 },
  { keyword: "burger king", categoryName: "Food", confidence: 0.9 },
  { keyword: "mcdonalds", categoryName: "Food", confidence: 0.9 },
  { keyword: "mcdonald", categoryName: "Food", confidence: 0.9 },
  { keyword: "subway", categoryName: "Food", confidence: 0.85 },
  { keyword: "starbucks", categoryName: "Food", confidence: 0.9 },
  { keyword: "chaayos", categoryName: "Food", confidence: 0.9 },
  { keyword: "haldiram", categoryName: "Food", confidence: 0.9 },
  { keyword: "bikanervala", categoryName: "Food", confidence: 0.9 },
  { keyword: "faasos", categoryName: "Food", confidence: 0.9 },
  { keyword: "box8", categoryName: "Food", confidence: 0.9 },
  { keyword: "behrouz", categoryName: "Food", confidence: 0.9 },
  { keyword: "oven story", categoryName: "Food", confidence: 0.9 },
  { keyword: "blue tokai", categoryName: "Food", confidence: 0.9 },
  { keyword: "third wave", categoryName: "Food", confidence: 0.9 },
  { keyword: "cafe coffee day", categoryName: "Food", confidence: 0.9 },
  { keyword: "ccd", categoryName: "Food", confidence: 0.85 },
  { keyword: "barista", categoryName: "Food", confidence: 0.9 },
  { keyword: "dunkin", categoryName: "Food", confidence: 0.9 },
  { keyword: "baskin robbins", categoryName: "Food", confidence: 0.9 },
  { keyword: "naturals ice", categoryName: "Food", confidence: 0.9 },
  { keyword: "taco bell", categoryName: "Food", confidence: 0.9 },
  { keyword: "wendy", categoryName: "Food", confidence: 0.85 },
  { keyword: "nandos", categoryName: "Food", confidence: 0.9 },
  { keyword: "barbeque nation", categoryName: "Food", confidence: 0.9 },
  { keyword: "biryani", categoryName: "Food", confidence: 0.85 },
  { keyword: "restaurant", categoryName: "Food", confidence: 0.8 },
  { keyword: "food", categoryName: "Food", confidence: 0.75 },
  { keyword: "eat", categoryName: "Food", confidence: 0.7 },
  { keyword: "dineout", categoryName: "Food", confidence: 0.85 },
  { keyword: "eazydiner", categoryName: "Food", confidence: 0.85 },
  { keyword: "magicpin", categoryName: "Food", confidence: 0.8 },
  { keyword: "rebel foods", categoryName: "Food", confidence: 0.9 },
  { keyword: "wow momo", categoryName: "Food", confidence: 0.9 },
  { keyword: "chai point", categoryName: "Food", confidence: 0.9 },

  // ────────────────────────────────────────────
  // Grocery & Supplies
  // ────────────────────────────────────────────
  { keyword: "bigbasket", categoryName: "Grocery & Supplies", confidence: 0.95 },
  { keyword: "big basket", categoryName: "Grocery & Supplies", confidence: 0.95 },
  { keyword: "blinkit", categoryName: "Grocery & Supplies", confidence: 0.95 },
  { keyword: "grofers", categoryName: "Grocery & Supplies", confidence: 0.95 },
  { keyword: "zepto", categoryName: "Grocery & Supplies", confidence: 0.95 },
  { keyword: "instamart", categoryName: "Grocery & Supplies", confidence: 0.95 },
  { keyword: "jiomart", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "dmart", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "d-mart", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "more retail", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "nature basket", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "spencer", categoryName: "Grocery & Supplies", confidence: 0.85 },
  { keyword: "reliance fresh", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "star bazaar", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "easy day", categoryName: "Grocery & Supplies", confidence: 0.85 },
  { keyword: "licious", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "country delight", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "milk basket", categoryName: "Grocery & Supplies", confidence: 0.9 },
  { keyword: "dunzo", categoryName: "Grocery & Supplies", confidence: 0.85 },
  { keyword: "grocery", categoryName: "Grocery & Supplies", confidence: 0.8 },
  { keyword: "supermarket", categoryName: "Grocery & Supplies", confidence: 0.8 },
  { keyword: "provision", categoryName: "Grocery & Supplies", confidence: 0.75 },

  // ────────────────────────────────────────────
  // Shopping & E-commerce
  // ────────────────────────────────────────────
  { keyword: "amazon", categoryName: "Shopping & Gifts", confidence: 0.85 },
  { keyword: "flipkart", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "myntra", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "ajio", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "meesho", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "snapdeal", categoryName: "Shopping & Gifts", confidence: 0.85 },
  { keyword: "nykaa", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "purplle", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "tata cliq", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "croma", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "reliance digital", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "vijay sales", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "decathlon", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "ikea", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "pepperfry", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "urban ladder", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "lenskart", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "firstcry", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "shoppers stop", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "lifestyle", categoryName: "Shopping & Gifts", confidence: 0.8 },
  { keyword: "westside", categoryName: "Shopping & Gifts", confidence: 0.85 },
  { keyword: "zara", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "h&m", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "uniqlo", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "pantaloons", categoryName: "Shopping & Gifts", confidence: 0.85 },
  { keyword: "max fashion", categoryName: "Shopping & Gifts", confidence: 0.85 },
  { keyword: "ferns n petals", categoryName: "Shopping & Gifts", confidence: 0.9 },
  { keyword: "fnp", categoryName: "Shopping & Gifts", confidence: 0.85 },
  { keyword: "archies", categoryName: "Shopping & Gifts", confidence: 0.85 },
  { keyword: "bewakoof", categoryName: "Shopping & Gifts", confidence: 0.85 },

  // ────────────────────────────────────────────
  // Travel & Going Out
  // ────────────────────────────────────────────
  { keyword: "uber", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "ola", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "rapido", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "makemytrip", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "mmt", categoryName: "Travel & Going Out", confidence: 0.85 },
  { keyword: "goibibo", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "cleartrip", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "irctc", categoryName: "Travel & Going Out", confidence: 0.95 },
  { keyword: "redbus", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "abhibus", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "yatra", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "easemytrip", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "indigo", categoryName: "Travel & Going Out", confidence: 0.85 },
  { keyword: "spicejet", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "air india", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "vistara", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "akasa", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "airasia", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "oyo", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "treebo", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "fabhotels", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "booking.com", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "agoda", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "hostelworld", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "zostel", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "metro", categoryName: "Travel & Going Out", confidence: 0.7 },
  { keyword: "ixigo", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "bookmyshow", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "paytm insider", categoryName: "Travel & Going Out", confidence: 0.85 },
  { keyword: "pvr", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "inox", categoryName: "Travel & Going Out", confidence: 0.9 },
  { keyword: "cinepolis", categoryName: "Travel & Going Out", confidence: 0.9 },

  // ────────────────────────────────────────────
  // Car & Vehicles (Fuel, Service, Parking)
  // ────────────────────────────────────────────
  { keyword: "shell", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "indian oil", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "iocl", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "hindustan petroleum", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "hpcl", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "bharat petroleum", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "bpcl", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "petrol", categoryName: "Car & Vehicles", confidence: 0.85 },
  { keyword: "diesel", categoryName: "Car & Vehicles", confidence: 0.85 },
  { keyword: "fuel", categoryName: "Car & Vehicles", confidence: 0.8 },
  { keyword: "fastag", categoryName: "Car & Vehicles", confidence: 0.95 },
  { keyword: "toll", categoryName: "Car & Vehicles", confidence: 0.85 },
  { keyword: "parking", categoryName: "Car & Vehicles", confidence: 0.85 },
  { keyword: "park+", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "gomechanic", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "mytvs", categoryName: "Car & Vehicles", confidence: 0.9 },
  { keyword: "car service", categoryName: "Car & Vehicles", confidence: 0.85 },
  { keyword: "auto repair", categoryName: "Car & Vehicles", confidence: 0.85 },
  { keyword: "tyre", categoryName: "Car & Vehicles", confidence: 0.8 },
  { keyword: "castrol", categoryName: "Car & Vehicles", confidence: 0.85 },

  // ────────────────────────────────────────────
  // Subscriptions
  // ────────────────────────────────────────────
  { keyword: "netflix", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "hotstar", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "disney+", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "prime video", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "amazon prime", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "spotify", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "youtube premium", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "youtube music", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "apple music", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "apple tv", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "icloud", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "google one", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "google storage", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "sonyliv", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "zee5", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "mxplayer", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "jio cinema", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "audible", categoryName: "Subscriptions", confidence: 0.95 },
  { keyword: "kindle", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "adobe", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "microsoft 365", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "notion", categoryName: "Subscriptions", confidence: 0.85 },
  { keyword: "chatgpt", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "openai", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "canva", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "grammarly", categoryName: "Subscriptions", confidence: 0.9 },
  { keyword: "linkedin premium", categoryName: "Subscriptions", confidence: 0.9 },

  // ────────────────────────────────────────────
  // Health & Medicine
  // ────────────────────────────────────────────
  { keyword: "apollo", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "1mg", categoryName: "Health & Medicine", confidence: 0.95 },
  { keyword: "pharmeasy", categoryName: "Health & Medicine", confidence: 0.95 },
  { keyword: "netmeds", categoryName: "Health & Medicine", confidence: 0.95 },
  { keyword: "practo", categoryName: "Health & Medicine", confidence: 0.9 },
  { keyword: "medplus", categoryName: "Health & Medicine", confidence: 0.9 },
  { keyword: "pharmacy", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "medicine", categoryName: "Health & Medicine", confidence: 0.8 },
  { keyword: "hospital", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "clinic", categoryName: "Health & Medicine", confidence: 0.8 },
  { keyword: "diagnostic", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "pathology", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "dr lal", categoryName: "Health & Medicine", confidence: 0.9 },
  { keyword: "thyrocare", categoryName: "Health & Medicine", confidence: 0.9 },
  { keyword: "healthifyme", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "cult.fit", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "curefit", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "gym", categoryName: "Health & Medicine", confidence: 0.8 },
  { keyword: "dental", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "optician", categoryName: "Health & Medicine", confidence: 0.85 },
  { keyword: "max healthcare", categoryName: "Health & Medicine", confidence: 0.9 },
  { keyword: "fortis", categoryName: "Health & Medicine", confidence: 0.9 },
  { keyword: "manipal hospital", categoryName: "Health & Medicine", confidence: 0.9 },
  { keyword: "medanta", categoryName: "Health & Medicine", confidence: 0.9 },

  // ────────────────────────────────────────────
  // Rent & Utilities
  // ────────────────────────────────────────────
  { keyword: "electricity", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "bescom", categoryName: "Rent & Utilities", confidence: 0.95 },
  { keyword: "tata power", categoryName: "Rent & Utilities", confidence: 0.95 },
  { keyword: "adani electricity", categoryName: "Rent & Utilities", confidence: 0.95 },
  { keyword: "msedcl", categoryName: "Rent & Utilities", confidence: 0.95 },
  { keyword: "bses", categoryName: "Rent & Utilities", confidence: 0.95 },
  { keyword: "water bill", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "piped gas", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "mahanagar gas", categoryName: "Rent & Utilities", confidence: 0.95 },
  { keyword: "indraprastha gas", categoryName: "Rent & Utilities", confidence: 0.95 },
  { keyword: "lpg", categoryName: "Rent & Utilities", confidence: 0.85 },
  { keyword: "indane gas", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "hp gas", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "jio fiber", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "airtel xstream", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "act fibernet", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "hathway", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "broadband", categoryName: "Rent & Utilities", confidence: 0.85 },
  { keyword: "wifi", categoryName: "Rent & Utilities", confidence: 0.8 },
  { keyword: "rent", categoryName: "Rent & Utilities", confidence: 0.85 },
  { keyword: "maintenance", categoryName: "Rent & Utilities", confidence: 0.8 },
  { keyword: "society", categoryName: "Rent & Utilities", confidence: 0.75 },
  { keyword: "jio recharge", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "airtel recharge", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "vi recharge", categoryName: "Rent & Utilities", confidence: 0.9 },
  { keyword: "mobile recharge", categoryName: "Rent & Utilities", confidence: 0.85 },

  // ────────────────────────────────────────────
  // Insurance
  // ────────────────────────────────────────────
  { keyword: "lic", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "icici prudential", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "hdfc life", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "max life", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "sbi life", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "star health", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "care health", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "digit insurance", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "acko", categoryName: "Insurance", confidence: 0.9 },
  { keyword: "policybazaar", categoryName: "Insurance", confidence: 0.85 },
  { keyword: "insurance", categoryName: "Insurance", confidence: 0.8 },
  { keyword: "premium", categoryName: "Insurance", confidence: 0.7 },

  // ────────────────────────────────────────────
  // EMIs
  // ────────────────────────────────────────────
  { keyword: "emi", categoryName: "EMIs", confidence: 0.85 },
  { keyword: "loan repayment", categoryName: "EMIs", confidence: 0.9 },
  { keyword: "home loan", categoryName: "EMIs", confidence: 0.9 },
  { keyword: "car loan", categoryName: "EMIs", confidence: 0.9 },
  { keyword: "personal loan", categoryName: "EMIs", confidence: 0.9 },
  { keyword: "education loan", categoryName: "EMIs", confidence: 0.9 },
  { keyword: "bajaj finserv", categoryName: "EMIs", confidence: 0.85 },
  { keyword: "bajaj finance", categoryName: "EMIs", confidence: 0.85 },

  // ────────────────────────────────────────────
  // Miscellaneous / Education / Services
  // ────────────────────────────────────────────
  { keyword: "unacademy", categoryName: "Miscellaneous", confidence: 0.8 },
  { keyword: "byju", categoryName: "Miscellaneous", confidence: 0.8 },
  { keyword: "udemy", categoryName: "Miscellaneous", confidence: 0.8 },
  { keyword: "coursera", categoryName: "Miscellaneous", confidence: 0.8 },
  { keyword: "upgrad", categoryName: "Miscellaneous", confidence: 0.8 },
  { keyword: "urbanclap", categoryName: "Miscellaneous", confidence: 0.8 },
  { keyword: "urban company", categoryName: "Miscellaneous", confidence: 0.8 },
  { keyword: "housejoy", categoryName: "Miscellaneous", confidence: 0.8 },
  { keyword: "paytm", categoryName: "Miscellaneous", confidence: 0.6 },
  { keyword: "phonepe", categoryName: "Miscellaneous", confidence: 0.5 },
  { keyword: "gpay", categoryName: "Miscellaneous", confidence: 0.5 },
  { keyword: "google pay", categoryName: "Miscellaneous", confidence: 0.5 },
];
