export const THRESHOLDS = {
  // Lifestyle Creep
  CREEP_WARNING_PCT: 15,
  CREEP_CRITICAL_PCT: 30,
  CREEP_SPIKE_MULTIPLIER: 3,

  // Category Drift
  DRIFT_CONSECUTIVE_MONTHS: 3,
  DRIFT_MIN_RISE_PCT: 10,

  // Merchant Shift
  SHIFT_TOP_N: 5,
  SHIFT_LOOKBACK_MONTHS: 3,

  // Weekend Warrior
  WEEKEND_MULTIPLIER: 1.5,
  WEEKEND_CONSECUTIVE_MONTHS: 2,

  // Micro-Leak
  MICRO_MAX_AMOUNT: 500,
  MICRO_MIN_FREQUENCY: 4,
  MICRO_WARNING_PCT: 5,
  MICRO_INFO_PCT: 2,

  // Budget Breach
  BREACH_MIN_DAY: 7,
  BREACH_TRIGGER_PCT: 60,
  BREACH_WARNING_PCT: 110,
  BREACH_CRITICAL_PCT: 130,

  // Goal Jeopardy
  JEOPARDY_SHORTFALL_MONTHS: 2,

  // Savings Rate Erosion
  EROSION_CONSECUTIVE_MONTHS: 3,
  EROSION_MIN_DROP_PCT: 2,

  // Credit Card Creep
  CC_WARNING_PCT: 40,
  CC_CRITICAL_PCT: 60,
  CC_GROWTH_MONTHS: 3,

  // Account Concentration
  CONCENTRATION_PCT: 80,

  // Recurring Growth
  RECURRING_GROWTH_PCT: 10,

  // Scoring Weights
  SCORE_IMPACT_WEIGHT: 0.4,
  SCORE_ACTIONABILITY_WEIGHT: 0.3,
  SCORE_URGENCY_WEIGHT: 0.2,
  SCORE_CONFIDENCE_WEIGHT: 0.1,

  // Dashboard
  DASHBOARD_MAX_INSIGHTS: 10,
  DASHBOARD_INITIAL_RENDER: 5,

  // Confidence
  MIN_MONTHS_FOR_TREND: 2,
  HIGH_CONFIDENCE_MONTHS: 6,

  // Classification
  CLASSIFICATION_MIN_OCCURRENCES: 2,
  CLASSIFICATION_CONFIRM_THRESHOLD: 0.85,
  CLASSIFICATION_AMOUNT_TOLERANCE: 0.1,

  // Nudges
  NUDGE_MAX_PER_SESSION: 2,
  NUDGE_MIN_AMOUNT: 1000,

  // Realistic Forecast
  FORECAST_EARLY_MONTH_DAYS: 7,
  FORECAST_HISTORICAL_WEIGHT_EARLY: 0.7,
  FORECAST_HISTORICAL_WEIGHT_LATE: 0.2,
} as const;

export type ThresholdKey = keyof typeof THRESHOLDS;
