import { Ionicons } from "@expo/vector-icons";
import { useMemo, useState } from "react";
import { FlatList, Linking, Pressable, View } from "react-native";
import { Card, Input, ScreenContainer, Text } from "@/components/ui";
import { useTheme } from "@/hooks/use-theme";

interface LicenseEntry {
  name: string;
  version: string;
  license: string;
  text: string | null;
}

// Generated by scripts/build-licenses.mjs — loaded only when this screen opens.
function loadLicenses(): LicenseEntry[] {
  return require("@/assets/data/open-source-licenses.json").packages as LicenseEntry[];
}

/** Settings → Open-source licences. Llama is pinned: Arth AI downloads it, it isn't an npm package. */
export default function LicensesScreen() {
  const theme = useTheme();
  const all = useMemo(loadLicenses, []);
  const [query, setQuery] = useState("");
  const [expanded, setExpanded] = useState<string | null>(null);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return q ? all.filter((p) => p.name.toLowerCase().includes(q) || p.license.toLowerCase().includes(q)) : all;
  }, [all, query]);

  return (
    <ScreenContainer padTop={false}>
      <FlatList
        data={filtered}
        keyExtractor={(p) => `${p.name}@${p.version}`}
        initialNumToRender={30}
        keyboardShouldPersistTaps="handled"
        contentContainerStyle={{ paddingHorizontal: 16, paddingBottom: 40 }}
        ListHeaderComponent={
          <View className="pt-4">
            <Card className="mb-4">
              <Text className="text-sm font-semibold text-foreground">Llama 3.2</Text>
              <Text className="text-xs text-muted-foreground mt-1 leading-4">
                Arth AI is built with Llama. Llama 3.2 is licensed under the Llama 3.2 Community
                License, Copyright © Meta Platforms, Inc. All Rights Reserved.
              </Text>
              <View className="flex-row mt-2" style={{ gap: 16 }}>
                <Pressable onPress={() => Linking.openURL("https://www.llama.com/llama3_2/license/")} hitSlop={8}>
                  <Text className="text-xs font-semibold text-primary">License</Text>
                </Pressable>
                <Pressable onPress={() => Linking.openURL("https://www.llama.com/llama3_2/use-policy/")} hitSlop={8}>
                  <Text className="text-xs font-semibold text-primary">Acceptable use policy</Text>
                </Pressable>
              </View>
            </Card>

            <Text className="text-sm text-muted-foreground mb-3 leading-5">
              Arth is built on {all.length} open-source packages and data sets. Tap one to read its
              licence.
            </Text>
            <Input placeholder="Search packages or licences" value={query} onChangeText={setQuery} containerClassName="mb-2" />
          </View>
        }
        renderItem={({ item }) => {
          const key = `${item.name}@${item.version}`;
          const open = expanded === key;
          return (
            <Pressable
              onPress={() => setExpanded(open ? null : key)}
              className="py-3 border-b border-border"
            >
              <View className="flex-row items-center">
                <View className="flex-1 mr-2">
                  <Text className="text-sm text-foreground">{item.name}</Text>
                  <Text className="text-xs text-muted-foreground">
                    {item.version ? `${item.version} · ` : ""}{item.license}
                  </Text>
                </View>
                <Ionicons name={open ? "chevron-up" : "chevron-down"} size={16} color={theme.mutedForeground} />
              </View>
              {open && (
                <Text className="text-xs text-muted-foreground mt-2 leading-4" selectable>
                  {item.text ?? `Licensed under ${item.license}. This package ships no separate licence file.`}
                </Text>
              )}
            </Pressable>
          );
        }}
        ListEmptyComponent={<Text className="text-sm text-muted-foreground py-6 text-center">No matches</Text>}
      />
    </ScreenContainer>
  );
}
