/**
 * Generates the CSS-variable block in `global.css` from `constants/design-tokens.js`.
 *
 * Run:  node scripts/generate-theme.js          (writes)
 *       node scripts/generate-theme.js --check  (exits non-zero if global.css is stale)
 *
 * CRITICAL — two rules this file exists to enforce, both learned the hard way:
 *
 *  1. The dark selector must be `.dark:root`, never `.dark`.
 *     NativeWind's normalize-selectors only recognises a dark root-variable block as `.dark:root`,
 *     `:root[class~="dark"]`, or a prefers-color-scheme media query. A bare `.dark {}` compiles to
 *     an ordinary class rule named "dark" that applies only if an element literally carries
 *     className="dark" — which `darkMode: "class"` never does, since the runtime switches on its
 *     own colorScheme observable. Result: total, silent loss of dark mode, no error anywhere.
 *
 *  2. The blocks must sit OUTSIDE `@layer base`.
 *     Inside that layer Tailwind purges any rule whose selector contains a class not found in the
 *     scanned content. `:root` has no class so it survives; `.dark:root` is dropped. Same silent
 *     failure as (1), from a completely different cause. Verified against tailwindcss 3.4.19.
 *
 * `scripts/verify-theme.js` asserts both by compiling the real output.
 */
const fs = require("fs");
const path = require("path");
const { SEMANTIC, RADIUS } = require("../constants/design-tokens.js");

const OUT = path.join(__dirname, "..", "global.css");
const MARK_START = "/* === GENERATED BY scripts/generate-theme.js — DO NOT EDIT BY HAND === */";
const MARK_END = "/* === END GENERATED === */";

const kebab = (s) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());

const vars = (scheme, indent) =>
  Object.entries(SEMANTIC[scheme])
    .map(([role, channels]) => indent + "--color-" + kebab(role) + ": " + channels + ";")
    .join("\n");

const css = [
  "@tailwind base;",
  "@tailwind components;",
  "@tailwind utilities;",
  "",
  MARK_START,
  ":root {",
  vars("light", "  "),
  "",
  "  --radius-control: " + RADIUS.control + ";",
  "  --radius-card: " + RADIUS.card + ";",
  "  --radius-sheet: " + RADIUS.sheet + ";",
  "}",
  "",
  "/* Selector MUST be `.dark:root`, and MUST stay outside @layer base. See file header. */",
  ".dark:root {",
  vars("dark", "  "),
  "}",
  MARK_END,
  "",
].join("\n");

/** Compare ignoring line endings — git autocrlf rewrites this file on checkout on Windows. */
const normalize = (s) => s.split("\r\n").join("\n");

if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (normalize(current) !== normalize(css)) {
    console.error("global.css is stale or hand-edited. Run: node scripts/generate-theme.js");
    process.exit(1);
  }
  console.log("global.css is up to date.");
} else {
  fs.writeFileSync(OUT, css, "utf8");
  console.log("Wrote " + OUT + " (" + Object.keys(SEMANTIC.light).length + " roles x 2 schemes).");
}
