/**
 * Generates the CSS-variable block in `global.css` from `constants/design-tokens.js`.
 *
 * Run:  node scripts/generate-theme.js          (writes)
 *       node scripts/generate-theme.js --check  (fails if global.css is stale)
 *
 * CRITICAL — the dark selector is `.dark:root`, not `.dark`.
 * NativeWind's `normalize-selectors` only recognises a dark root-variable block as
 * `.dark:root`, `:root[class~="dark"]`, or a prefers-color-scheme media query. A bare `.dark {}`
 * compiles to an ordinary class rule named "dark" that applies only if some element literally
 * carries className="dark" — which `darkMode: "class"` never does, because the runtime switches on
 * its own colorScheme observable instead. The result is a silent, total loss of dark mode with no
 * error at build or runtime. `scripts/verify-theme.js` guards against a regression here.
 */
const fs = require("fs");
const path = require("path");
const { SEMANTIC, RADIUS } = require("../constants/design-tokens.js");

const OUT = path.join(__dirname, "..", "global.css");
const MARK_START = "/* === GENERATED BY scripts/generate-theme.js — DO NOT EDIT BY HAND === */";
const MARK_END = "/* === END GENERATED === */";

const vars = (scheme, indent) =>
  Object.entries(SEMANTIC[scheme])
    .map(([role, channels]) => `${indent}--color-${kebab(role)}: ${channels};`)
    .join("\n");

function kebab(s) {
  return s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());
}

/*
 * NOTE — the variable blocks sit OUTSIDE `@layer base` deliberately.
 * Inside `@layer base`, Tailwind purges any rule whose selector contains a class that does not
 * appear in the scanned content. `:root` has no class so it survives, but `.dark:root` is silently
 * dropped — producing a light-only build with no error. At the top level the rules pass through
 * untouched. Verified against tailwindcss 3.4.19.
 */
const block = `${MARK_START}
:root {
${vars("light", "  ")}

  --radius-control: ${RADIUS.control};
  --radius-card: ${RADIUS.card};
  --radius-sheet: ${RADIUS.sheet};
}

/* Selector MUST be \`.dark:root\` — see the header of this file. */
.dark:root {
${vars("dark", "  ")}
}
${MARK_END}`;

const css = `@tailwind base;
@tailwind components;
@tailwind utilities;

${block}
`;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== css) {
    console.error(
      "global.css is stale or was hand-edited.\nRun: node scripts/generate-theme.js",
    );
    process.exit(1);
  }
  console.log("global.css is up to date.");
} else {
  fs.writeFileSync(OUT, css, "utf8");
  console.log(`Wrote ${OUT} (${Object.keys(SEMANTIC.light).length} roles x 2 schemes).`);
}
